  server:
    port: 8011

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8888/eureka,http://localhost:8889/eureka
  

  version:  UserProvider66666
  spring:

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    application:
      name: UserProvider1
    datasource:
      url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource


 








